image: python:3.6

variables:
    DOCKER_DRIVER: overlay2
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

stages:
    - pages
    - lint
    - test
    - pypi

before_script:
    # Python 3.5 installation of pyyaml breaks without Python.h
    - apt update && apt install -y --no-install-recommends libpython3.5-dev python3.5-dev openssh-client
    - pip install poetry
    - poetry config settings.virtualenvs.create false
    - pip install tox

.test:
    variables:
        APP_ENV: "testing"

lint:
    extends: .test
    stage: lint
    script:
        - tox -e lint

test:
    extends: .test
    stage: test
    coverage: '/^TOTAL.*\s+(\d+\%)$/'
    script:
        - tox -e py

pages:
    extends: .test
    stage: pages
    script:
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - git fetch
        - git clone --branch gh-pages ${CI_REPOSITORY_URL} gh-pages
        - tox -e gh-pages
        - git config --global user.email "openkiwi@unbabel.com"
        - git config --global user.name "GitLab CI"
 
        - cd gh-pages; git add .; git commit -m "Update docs"
        - git push git@github.com:Unbabel/OpenKiwi.git gh-pages
    only:
        - master
    when: manual

pypi:
    # Upload to internal PyPI index
    stage: pypi
    script:
        - poetry config repositories.unbabel ${UNBABEL_PYPI_REPOSITORY_URL}
        - poetry config http-basic.unbabel ${UNBABEL_PYPI_REPOSITORY_USERNAME} ${UNBABEL_PYPI_REPOSITORY_PASSWORD}
        - poetry publish --build -r unbabel
    only:
        - tags  # Only allow this stage to be run when a new tag is pushed
