run:
    experiment_name: Predictor WMT20 en_de
    seed: 42
    mlflow_tracking_uri: mlruns
    use_mlflow: false

trainer:
    gpus: -1
    log_interval: 100

    resume: false
    epochs: 5

    checkpoint:
        validation_steps: 200
        save_top_k: 1
        early_stop_patience: 8

defaults:
    - data: wmt20.qe.en_de

system:
    class_name: Predictor

    num_data_workers: 4
    batch_size:
        train: 32
        valid: 32

    model:
        encoder:
            encode_source: false
            hidden_size: 400
            rnn_layers: 2
            embeddings:
                source:
                    dim: 200
                target:
                    dim: 200
            out_embeddings_dim: 200
            share_embeddings: false
            dropout: 0.5
            use_mismatch_features: false

    optimizer:
        class_name: adam
        learning_rate: 0.001
        learning_rate_decay: 0.6
        learning_rate_decay_start: 2

    data_processing:
        vocab:
            min_frequency: 1
            max_size: 60_000
