run:
    experiment_name: PredictorEstimator WMT20 Target en_de.nmt
    seed: 42
    mlflow_tracking_uri: mlruns/
    # output_dir: runs/predictor-estimator  # mlflow will create one if this is null

trainer:
    gpus: -1

    resume: false
    epochs: 10
    log_interval: 50

    main_metric:
        - PEARSON
        - target_tags_F1_MULT

    checkpoint:
        validation_steps: 100
        save_top_k: 1
        early_stop_patience: 8

defaults:
    - data: wmt20.qe.en_de

system:
    class_name: PredictorEstimator

    batch_size: 32
    num_data_workers: 4

    load_encoder: best_model.torch

    model:
        encoder:
            encode_source: false
            hidden_size: 400
            rnn_layers: 2
            embeddings:
                source:
                    dim: 200
                target:
                    dim: 200
            out_embeddings_dim: 200
            share_embeddings: false
            dropout: 0.5
            use_mismatch_features: false

        decoder:
            hidden_size: 125
            rnn_layers: 1
            use_mlp: true
            dropout: 0.0

        outputs:
            word_level:
                target: true
                gaps: false
                source: false
                class_weights:
                    target_tags:
                        BAD: 5.0
                    gap_tags:
                        BAD: 5.0
                    source_tags:
                        BAD: 3.0
            sentence_level:
                hter: true
                use_distribution: true
                binary: false

        tlm_outputs:
            fine_tune: true

    optimizer:
        class_name: adam
        learning_rate: 0.001
        learning_rate_decay: 0.6
        learning_rate_decay_start: 2

    data_processing:
        vocab:
            min_frequency: 1
            max_size: 60_000
