run:
    experiment_name: XLM WMT20 EN-DE
    seed: 42
    use_mlflow: false

trainer:
    deterministic: true
    gpus: -1
    epochs: 10

    main_metric:
        - WMT19_MCC
        - PEARSON

    gradient_max_norm: 1.
    gradient_accumulation_steps: 1

    amp_level: O2
    precision: 16

    log_interval: 100
    checkpoint:
        validation_steps: 0.2
        early_stop_patience: 10

defaults:
    - data: wmt20.qe.en_de

system:
    class_name: XLM

    batch_size: 8
    num_data_workers: 4

    model:
        encoder:
            model_name: xlm-mlm-tlm-xnli15-1024
            interleave_input: false
            freeze: false
            use_mlp: false

        decoder:
            hidden_size: 768
            bottleneck_size: 768
            dropout: 0.1

        outputs:
            word_level:
                target: true
                gaps: true
                source: true
                class_weights:
                    target_tags:
                        BAD: 3.0
                    gap_tags:
                        BAD: 5.0
                    source_tags:
                        BAD: 3.0
            sentence_level:
                hter: true
                use_distribution: false
                binary: false
            n_layers_output: 2
            sentence_loss_weight: 2

        tlm_outputs:
            fine_tune: false

    optimizer:
        class_name: adamw
        learning_rate: 1e-05
        warmup_steps: 0.1
        training_steps: 12000

    data_processing:
        share_input_fields_encoders: true
