run:
    experiment_name: XLM-Roberta WMT20 EN-DE
    seed: 42
    use_mlflow: false

trainer:
    gpus: -1
    epochs: 10

    log_interval: 100

    main_metric:
        - WMT19_MCC
        - PEARSON

    checkpoint:
        validation_steps: 0.2
        early_stop_patience: 10

    gradient_max_norm: 1.

defaults:
    - data: wmt20.qe.en_de

system:
    class_name: XLMRoberta

    batch_size: 8
    num_data_workers: 4

    model:
        encoder:
            model_name: xlm-roberta-base
            interleave_input: false
            freeze: false
            use_mlp: false
            pooling: mixed
            freeze_for_number_of_steps: 1000

        decoder:
            hidden_size: 768
            bottleneck_size: 768
            dropout: 0.1

        outputs:
            word_level:
                target: true
                gaps: true
                source: true
                class_weights:
                    target_tags:
                        BAD: 3.5
                    gap_tags:
                        BAD: 3.5
                    source_tags:
                        BAD: 3.5
            sentence_level:
                hter: true
                use_distribution: false
                binary: false
            dropout: 0.1

        tlm_outputs:
            fine_tune: false

    optimizer:
        class_name: adamw
        learning_rate: 1e-05
        warmup_steps: 0.1
        training_steps: 7000

    data_processing:
        share_input_fields_encoders: true
