# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

# import sphinx_autodoc_typehints
import os
import sys

import toml

from m2r import MdInclude
# from recommonmark.transform import AutoStructify

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# sys.path.insert(0, os.path.abspath('..'))

# Get the project root dir, which is the parent dir of this
cwd = os.getcwd()
project_root = os.path.dirname(cwd)

# Insert the project root dir as the first element in the PYTHONPATH.
# This lets us ensure that the source package is imported, and that its
# version is used.
sys.path.insert(0, project_root)

metadata = toml.load(os.path.join(project_root, 'pyproject.toml'))
about = metadata['tool']['poetry']

project = about['name']
copyright = (
    '2019-2020 Unbabel. All rights reserved. '
    'Source code available under the AGPL-3.0.'
)
author = '; '.join(about['authors'])

# The short X.Y version
version = '%s' % (about['version'])
# The full version, including alpha/beta/rc tags
release = '%s' % (about['version'])

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'autoapi.extension',
    'sphinx.ext.autosummary',
    'sphinx.ext.napoleon',
    'sphinx.ext.autodoc',
    'sphinx_autodoc_typehints',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'recommonmark',
    # 'sphinx.ext.githubpages',
    # 'sphinx_paramlinks',
    # 'sphinx-issues',
    # 'sphinx-pydantic',
    # 'sphinx-jsonschema',
    # 'sphinx_automodapi.automodapi',
    # 'sphinx_automodapi.smart_resolver',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None

# -- Options for HTML output -------------------------------------------------

html_logo = '_static/img/openkiwi-logo-horizontal.svg'
html_favicon = '_static/img/openkiwi-logo-icon.ico'

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'pydata_sphinx_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the documentation.
html_theme_options = {
    # 'canonical_url': '',
    # 'analytics_id': 'UA-XXXXXXX-1',  #  Provided by Google in your dashboard
    # 'logo_only': False,
    # 'display_version': True,
    # 'prev_next_buttons_location': 'bottom',
    # 'style_external_links': False,
    # 'vcs_pageview_mode': '',
    # 'style_nav_header_background': 'white',
    # Toc options
    # 'collapse_navigation': False,
    # 'sticky_navigation': True,
    # 'navigation_depth': 4,
    # 'includehidden': True,
    # 'titles_only': False
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'OpenKiwiDoc'

# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'openkiwi', 'OpenKiwi Documentation',
     [author], 1)
]

# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
# intersphinx_mapping = {'https://docs.python.org/': None}
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'torch': ('https://pytorch.org/docs/master/', None),
    'numpy': ('https://docs.scipy.org/doc/numpy/', None),
}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for Recommonmark and m2r-----------------------------------------

# -- Options for autodoc/autosummary/automodapi extensions ---------------------------------------

# autodoc_typehints = 'description'  # For when sphinx 3.1 comes out
autodoc_typehints = 'signature'

autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    # 'special-members': '__init__',
    'undoc-members': False,
    'exclude-members': '__weakref__',
    'inherited-members': False,
    'show-inheritance': False,
}

autosummary_generate = True
autosummary_imported_members = False

# autodoc-typehints
set_type_checking_flag = True
always_document_param_types = True
typehints_document_rtype = True

napoleon_use_param = True

autoapi_dirs = ['../kiwi']
autoapi_generate_api_docs = True
autoapi_keep_files = True
autoapi_options = [
    'show-module-summary',
    'members',
    'undoc-members',
    'private-members',
    'show-inheritance',
    'special-members',
]


def setup(app):
    # app.add_config_value('recommonmark_config', {
    #     # 'url_resolver': lambda url: github_doc_root + url,
    #     # 'auto_toc_tree_section': 'Contents',
    #     'enable_eval_rst': True,
    # }, True)
    # app.add_transform(AutoStructify)

    # from m2r to make `mdinclude` work
    # https://github.com/life4/deal/commit/7f33cbc595ed31519cefdfaaf6f415dada5acd94
    app.add_config_value('no_underscore_emphasis', False, 'env')
    app.add_config_value('m2r_parse_relative_links', False, 'env')
    app.add_config_value('m2r_anonymous_references', False, 'env')
    app.add_config_value('m2r_disable_inline_math', False, 'env')
    app.add_directive('mdinclude', MdInclude)
    # app.add_stylesheet('css/unbabel.css')
